version: '3.9'

services:
  backend:
    user: root
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile 
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000"]
    volumes:
      - ./backend:/home/valuedriven/backend
    ports:
      - "8000:8000"
      - "5678:5678"
    env_file:
      - ./backend/.env.local
    restart: always

  frontend:
    user: root
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/home/valuedriven/frontend
    ports:
      - "5173:5173"
    restart: always
